services:
    refs-php:
        container_name: refs-php
        build: ./docker/php
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
        depends_on:
            - refs-db
            - refs-rabbitmq
        networks: [refs_net]

    refs-nginx:
        container_name: refs-nginx
        build: ./docker/nginx
        ports:
            - "8081:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - refs-php
        networks: [refs_net]

    refs-db:
        container_name: refs-db
        build: ./docker/db
        environment:
            POSTGRES_DB: refs_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - "5433:5432"
        volumes:
            - ./docker/db/data:/var/lib/db
        networks: [refs_net]

    refs-pgadmin:
        container_name: refs-pgadmin
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5051:80"
        depends_on:
            - refs-db
        networks: [refs_net]

    refs-rabbitmq:
        container_name: refs-rabbitmq
        image: rabbitmq:3-management
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password
        ports:
            - "5673:5672"
            - "15673:15672"
        networks: [refs_net]

networks:
    refs_net:
        driver: bridge
